[site]
title = "Project RC"
subtitle = "一只腊鸡的技术成长。"
author = "Richard Chien"
copyright_year = "2013-2022"
timezone = "Asia/Shanghai"
language = "zh-Hans"

[config]
posts_per_index_page = 999999
disqus_enabled = true
disqus_short_name = "richardchien"
google_analytics_enabled = true
google_analytics_id = "G-681FDHED04"
